apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ms-product-03-hpa
  namespace: sabado
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ms-product-03
  minReplicas: 1
  maxReplicas: 2
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50