apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: sabado
spec:
  serviceName: postgres
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:12.20-alpine3.20
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: curso
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: "1234"
            - name: TZ
              value: America/Bogota
          volumeMounts: 
            - name: postgres-pv-storage
              mountPath: /var/lib/postgresql/data
              subPath: data
      volumes:
        - name: postgres-pv-storage
          persistentVolumeClaim:
            claimName: postgres-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: sabado
spec:
  selector:
    app: postgres
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pv-claim
  namespace: sabado
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi