apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-product-03
  namespace: sabado
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-product-03
  template:
    metadata:
      labels:
        app: ms-product-03
    spec:
      containers:
      - name: ms-product-03
        image: mauron/ms-producto:7-postgres
        envFrom:
        - configMapRef:
            name: postgres-config
        - secretRef:
            name: postgres-secret
        ports:
        - containerPort: 8080
        