apiVersion: v1
kind: Service
metadata:
  name: ms-product-03
  namespace: sabado
spec:
  selector:
    app: ms-product-03
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080