name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    
    runs-on: profe

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 11 for x64
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        architecture: x64
        
    - name: Run the Maven verify phase
      run: mvn package
      
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ms-producto:$(date +%s)
