name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 21 for x64
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        architecture: x64
        
    - name: Run the Maven verify phase
      run: mvn package -DskipTests
      
    - name: Build the Docker image
      run: docker build . -t ms-producto:${{ github.run_number}}