name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 21 for x64
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        architecture: x64
        
    - name: Run the Maven verify phase
      run: mvn package -DskipTests
      
    - name: Build the Docker image
      run: docker build . -t ms-producto:${{ github.run_number}}

    - name: Build the Docker image
      run: docker login registrysabado.azurecr.io -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }} 

    - name: Push the Docker image
      run:  |
        docker tag ms-producto:${{ github.run_number}} registrysabado.azurecr.io/ms-producto:${{ github.run_number}} 
        docker push registrysabado.azurecr.io/ms-producto:${{ github.run_number}}

  deploy:
       
    runs-on: ubuntu-latest
    needs: build
    steps:

    - name: Create kubeconfig
      run: |
        mkdir ${HOME}/.kube
        echo ${{ secrets.AZURE_CREDENTIALS }} | base64 --decode > ${HOME}/.kube/config
        cat ${HOME}/.kube/config
    
    - name: Deploy to K8s
      run: kubectl apply -f k8s/
